name: CI - CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image 
        uses: docker/build-push-action@v6.18.0
        with: 
          context: .
          push: true
          tags: igoor1/your-disc:${{ github.run_number }}
    